name: Angular CI with SonarCloud and Docker Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

  build:
    name: Build Angular project
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular (prod configuration)
        run: npm run build -- --configuration=production

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests with coverage (ignore errors)
        run: |
          npm run test -- --watch=false --code-coverage || echo "Tests failed but continuing..."

  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install SonarCloud scanner
        run: npm install -g sonar-scanner

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner

  docker-deploy:
    name: Build & Push Docker Image to Nexus
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Nexus Docker Registry
        env:
          NEXUS_URL: ${{ secrets.NEXUS_URL }}  # ex: https://af8a-2c0f-f698-c137-da1c-4542-ce20-e080-db75.ngrok-free.app
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          echo "$NEXUS_PASSWORD" | docker login $NEXUS_URL -u $NEXUS_USERNAME --password-stdin

      - name: Build Docker image
        env:
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
        run: docker build -t ${NEXUS_URL#https://}/frontapp:latest .

      - name: Push Docker image
        env:
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
        run: docker push ${NEXUS_URL#https://}/frontapp:latest